export const adminNavItems = [
  {
    key: 'dashboard',
    label: '运营看板',
    icon: 'BK',
    path: '/admin/dashboard',
    permission: 'dashboard:view',
  },
  {
    key: 'enterprise-audit',
    label: '企业资质审核',
    icon: 'QY',
    path: '/admin/enterprise-audit',
    permission: 'enterpriseAudit:view',
  },
  {
    key: 'job-audit',
    label: '岗位审核',
    icon: 'GW',
    path: '/admin/job-audit',
    permission: 'jobAudit:view',
  },
  {
    key: 'users',
    label: '用户管理',
    icon: 'YH',
    path: '/admin/users',
    permission: 'users:view',
  },
  {
    key: 'applications',
    label: '流程监控',
    icon: 'LC',
    path: '/admin/applications',
    permission: 'applications:view',
  },
  {
    key: 'reports',
    label: '举报处理',
    icon: 'JB',
    path: '/admin/reports',
    permission: 'reports:view',
  },
  {
    key: 'reviews',
    label: '评价管理',
    icon: 'PJ',
    path: '/admin/reviews',
    permission: 'reviews:view',
  },
  {
    key: 'penalties',
    label: '处罚记录',
    icon: 'CF',
    path: '/admin/penalties',
    permission: 'penalties:view',
  },
  {
    key: 'notifications',
    label: '通知中心',
    icon: 'TZ',
    path: '/admin/notifications',
    permission: 'notifications:view',
  },
  {
    key: 'rules',
    label: '审核策略',
    icon: 'CL',
    path: '/admin/rules',
    permission: 'rules:view',
  },
  {
    key: 'logs',
    label: '系统日志',
    icon: 'RZ',
    path: '/admin/logs',
    permission: 'logs:view',
  },
  {
    key: 'permissions',
    label: '权限中心',
    icon: 'RB',
    path: '/admin/permissions',
    permission: 'permissions:view',
  },
]
